name: Docker Compose CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: zip-zap-shotter
    steps:
      - uses: actions/checkout@v4

      - name: Debug - Check variables
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is empty";
          else
            echo "DOCKER_USERNAME is set";
          fi

          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is empty";
          else
            echo "DOCKER_PASSWORD is set and not empty";
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker compose build
          docker tag db registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker tag app registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker tag nginx registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
